spring.application.name=Wallet
spring.datasource.password=oluwakemisola098
paystack.secret.key=sk_test_0a992c17a3b1cf2ffa217753d4c1542206d7309d
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/DrWallet



#paystack.initiate.payment.url=https://api.paystack.co/transaction/initialize
#paystack.verify.payment.url=https://api.paystack.co/transaction/verify/


#paystack.api.key=sk_test_dd6b2b04493446cc618788ba1b1a67231987a5b2